In [1]:
import numpy as np

In [6]:
mu1 = np.array([1,4,2,6,9,4])
mu2 = np.array([2,3,6,7,3,2])

D1 = [1,3,5,7,8,9]
D2 = [11,13,15,17,18,19]


C = mu1>mu2

C

array([False,  True, False, False,  True,  True])

In [ ]:
D3 = np.where(C,D1,D2)  # Replacing pixels of D1 by corresponding pixels of D2 where C is True
D3

array([11,  3, 15, 17,  8,  9])

In [ ]:
D4 = np.where(C,D2,D1) # replacing pixels of D1 by corresponding pixels of D2 where C = True 
D4

array([ 1, 13,  5,  7, 18, 19])

In [10]:
mu_red = np.where(C,mu1,mu2)  # Replacing pixels of D2 by corresponding pixels of D1 where C is False
mu_red

array([2, 4, 6, 7, 9, 4])

In [11]:
mu_blue = np.where(C,mu2,mu1)  # Replacing pixels of D2 by corresponding pixels of D1 where C is False
mu_blue

array([1, 3, 2, 6, 3, 2])